In [58]:
import numpy as np
import pandas as pd

dataset = pd.read_csv("Fish.csv", delimiter='\t')

In [59]:
import tensorflow

In [60]:
print(tensorflow.__version__)

1.14.0


In [61]:
dataset

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5     Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6     Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7     Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8     Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9     Bream   500.0     28.5     30.7     36.2  14.2266  4.9594
10    Bream   475.0     28.4     31.0     36.2  14.2628  5.1042
11    Bream   500.0     28.7     31.0     36.2  14.3714  4.8146
12    Bream   500.0     29.1     31.5     36.4  13.7592  4.3680
13    Bream   340.0     29.5     32.0     37.3  13.9129  5.0728
14    Bream   600.0     29.4     32.0     37.2  14.9544  5.1708
15    Bream   600.0     29.4     32.0     37.2  15.4380  5.5800
16    Bream   700.0     30.4     33.0     38.3  14.8604  5.2854
17    Bream   700.0     30.4     33.0     38.5  14.9380  5.1975
18    Bream   610.0     30.9     33.5     38.6  15.6330  5.1338
19    Bream   650.0     31.0     33.5     38.7  14.4738  5.7276
20    Bream   575.0     31.3     34.0     39.5  15.1285  5.5695
21    Bream   685.0     31.4     34.0     39.2  15.9936  5.3704
22    Bream   620.0     31.5     34.5     39.7  15.5227  5.2801
23    Bream   680.0     31.8     35.0     40.6  15.4686  6.1306
24    Bream   700.0     31.9     35.0     40.5  16.2405  5.5890
25    Bream   725.0     31.8     35.0     40.9  16.3600  6.0532
26    Bream   720.0     32.0     35.0     40.6  16.3618  6.0900
27    Bream   714.0     32.7     36.0     41.5  16.5170  5.8515
28    Bream   850.0     32.8     36.0     41.6  16.8896  6.1984
29    Bream  1000.0     33.5     37.0     42.6  18.9570  6.6030
..      ...     ...      ...      ...      ...      ...     ...
129    Pike   300.0     31.7     34.0     37.8   5.7078  4.1580
130    Pike   300.0     32.7     35.0     38.8   5.9364  4.3844
131    Pike   300.0     34.8     37.3     39.8   6.2884  4.0198
132    Pike   430.0     35.5     38.0     40.5   7.2900  4.5765
133    Pike   345.0     36.0     38.5     41.0   6.3960  3.9770
134    Pike   456.0     40.0     42.5     45.5   7.2800  4.3225
135    Pike   510.0     40.0     42.5     45.5   6.8250  4.4590
136    Pike   540.0     40.1     43.0     45.8   7.7860  5.1296
137    Pike   500.0     42.0     45.0     48.0   6.9600  4.8960
138    Pike   567.0     43.2     46.0     48.7   7.7920  4.8700
139    Pike   770.0     44.8     48.0     51.2   7.6800  5.3760
140    Pike   950.0     48.3     51.7     55.1   8.9262  6.1712
141    Pike  1250.0     52.0     56.0     59.7  10.6863  6.9849
142    Pike  1600.0     56.0     60.0     64.0   9.6000  6.1440
143    Pike  1550.0     56.0     60.0     64.0   9.6000  6.1440
144    Pike  1650.0     59.0     63.4     68.0  10.8120  7.4800
145   Smelt     6.7      9.3      9.8     10.8   1.7388  1.0476
146   Smelt     7.5     10.0     10.5     11.6   1.9720  1.1600
147   Smelt     7.0     10.1     10.6     11.6   1.7284  1.1484
148   Smelt     9.7     10.4     11.0     12.0   2.1960  1.3800
149   Smelt     9.8     10.7     11.2     12.4   2.0832  1.2772
150   Smelt     8.7     10.8     11.3     12.6   1.9782  1.2852
151   Smelt    10.0     11.3     11.8     13.1   2.2139  1.2838
152   Smelt     9.9     11.3     11.8     13.1   2.2139  1.1659
153   Smelt     9.8     11.4     12.0     13.2   2.2044  1.1484
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [62]:
dataset.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [63]:
x = dataset.iloc[:,1:].values
y = dataset.iloc[:,0:1].values

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer([("one", OneHotEncoder(), [0])], remainder="passthrough")

In [65]:
y=ct.fit_transform(y)


In [66]:
y.shape

(159, 7)

In [67]:
y=y.toarray()

In [68]:
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [70]:
x_train.shape

(127, 6)

In [71]:
y_train.shape

(127, 7)

In [76]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [72]:

from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

categorical=Sequential()
categorical.add(Dense( units= 6, kernel_initializer= "random_uniform", activation="relu"))

In [73]:
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))
categorical.add(Dense( units= 12, kernel_initializer= "random_uniform", activation="relu"))

In [74]:
categorical.add(Dense( units= 7, kernel_initializer= "random_uniform", activation="softmax"))

In [75]:
categorical.compile(optimizer="rmsprop", loss="categorical_crossentropy", metrics=["accuracy"])

In [77]:
categorical.fit(x_train,y_train, epochs=100)

Epoch 1/100
127/127 [==============================] - 1s 8ms/sample - loss: 1.9434 - acc: 0.2913
Epoch 2/100
127/127 [==============================] - 0s 71us/sample - loss: 1.9389 - acc: 0.3701
Epoch 3/100
127/127 [==============================] - 0s 63us/sample - loss: 1.9352 - acc: 0.3701
Epoch 4/100
127/127 [==============================] - 0s 94us/sample - loss: 1.9316 - acc: 0.3701
Epoch 5/100
127/127 [==============================] - 0s 0s/sample - loss: 1.9280 - acc: 0.3701
Epoch 6/100
127/127 [==============================] - 0s 108us/sample - loss: 1.9241 - acc: 0.3701
Epoch 7/100
127/127 [==============================] - 0s 44us/sample - loss: 1.9199 - acc: 0.3701
Epoch 8/100
127/127 [==============================] - 0s 63us/sample - loss: 1.9152 - acc: 0.3701
Epoch 9/100
127/127 [==============================] - 0s 42us/sample - loss: 1.9098 - acc: 0.3701
Epoch 10/100
127/127 [==============================] - 0s 31us/sample - loss: 1.9040 - acc: 0.3701
Epoch 11/10

127/127 [==============================] - 0s 39us/sample - loss: 1.5300 - acc: 0.4488
Epoch 84/100
127/127 [==============================] - 0s 55us/sample - loss: 1.5256 - acc: 0.4488
Epoch 85/100
127/127 [==============================] - 0s 39us/sample - loss: 1.5253 - acc: 0.4488
Epoch 86/100
127/127 [==============================] - 0s 47us/sample - loss: 1.5232 - acc: 0.4567
Epoch 87/100
127/127 [==============================] - 0s 47us/sample - loss: 1.5231 - acc: 0.4409
Epoch 88/100
127/127 [==============================] - 0s 31us/sample - loss: 1.5205 - acc: 0.4567
Epoch 89/100
127/127 [==============================] - 0s 39us/sample - loss: 1.5190 - acc: 0.4488
Epoch 90/100
127/127 [==============================] - 0s 47us/sample - loss: 1.5165 - acc: 0.4567
Epoch 91/100
127/127 [==============================] - 0s 55us/sample - loss: 1.5150 - acc: 0.4567
Epoch 92/100
127/127 [==============================] - 0s 31us/sample - loss: 1.5131 - acc: 0.4567
Epoch 93/100


In [79]:
x_test

array([[ 0.03079721,  0.19914534,  0.21275144,  0.39401436,  0.86816042,
         0.20902029],
       [-1.14637952, -0.70075761, -0.7139078 , -0.6978938 , -0.54931349,
        -0.59608381],
       [-0.63325121, -0.43915791, -0.42127857, -0.50099233, -0.5951226 ,
        -0.37146795],
       [-0.66343522, -0.54379779, -0.51882164, -0.47414212, -0.42158799,
        -0.31414098],
       [ 0.53185192,  0.65956081,  0.65169528,  0.52826536,  0.31591123,
         1.2301382 ],
       [ 1.57018216,  1.1827602 ,  1.18818221,  1.06526938,  0.65307269,
         1.7339298 ],
       [ 1.26834197,  0.8374486 ,  0.83702713,  0.80571744,  0.66021177,
         1.3420852 ],
       [-0.24085896,  0.95255247,  0.9248159 ,  0.82361757, -0.59205646,
        -0.1941333 ],
       [ 1.7965623 ,  1.22461615,  1.28572528,  1.36957165,  2.23314378,
         1.44657309],
       [-0.79926331, -0.70075761, -0.66513626, -0.724744  , -0.67692458,
        -0.62261182],
       [-0.54269915,  0.45028105,  0.43710051,  0.

In [80]:
ypred = categorical.predict(x_test)

In [81]:
ypred

array([[3.85645598e-01, 1.75687484e-02, 3.63640636e-01, 1.72478467e-01,
        2.99740341e-02, 1.70240495e-02, 1.36685157e-02],
       [1.50795281e-01, 1.17837511e-01, 2.29261577e-01, 1.20991446e-01,
        1.52246267e-01, 1.38515815e-01, 9.03521180e-02],
       [1.50703356e-01, 1.17894761e-01, 2.29164004e-01, 1.20944969e-01,
        1.52303919e-01, 1.38593435e-01, 9.03955251e-02],
       [1.50256783e-01, 1.18173197e-01, 2.28689551e-01, 1.20718911e-01,
        1.52583972e-01, 1.38971031e-01, 9.06065777e-02],
       [4.16270852e-01, 1.17411055e-02, 3.62123668e-01, 1.68701947e-01,
        2.09929347e-02, 1.10122794e-02, 9.15719662e-03],
       [5.32622695e-01, 1.70075614e-03, 3.21277052e-01, 1.37919322e-01,
        3.76311899e-03, 1.37564458e-03, 1.34136679e-03],
       [4.91078466e-01, 3.62024293e-03, 3.40947688e-01, 1.51030347e-01,
        7.38083804e-03, 3.09955678e-03, 2.84300046e-03],
       [2.17254162e-01, 8.00334141e-02, 2.91081667e-01, 1.49342790e-01,
        1.11294828e-01, 8

In [82]:
y_test

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
 

In [83]:
ypred[0]

array([0.3856456 , 0.01756875, 0.36364064, 0.17247847, 0.02997403,
       0.01702405, 0.01366852], dtype=float32)

In [85]:
categorical.save("Fishes.h5")