In [1]:
import pandas as pd
import nltk
import re

In [2]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [23]:
df=pd.read_csv('ramen-ratings.csv')
ps=PorterStemmer()
data=[]

In [27]:
for i in range(0,1000):
  Brand=df['Brand'][i]

  #remove uneccessary things
  Brand=re.sub('[^a-zA-Z]',' ',Brand )

  #Lower case text
  Brand=Brand.lower()

  #split the text
  Brand=Brand.split()

  #Stemming & Remove Stopwords
  Brand=[ps.stem(word) for word in Brand if not word in 
          set(stopwords.words('english'))]

  Brand=' '.join(Brand)
  data.append(Brand)

In [28]:
import numpy as np

In [29]:
#Tokenization or Vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000)

In [36]:
x=cv.fit_transform(data).toarray()
y=df.iloc[:,1:2].values

In [31]:
print(x.shape)
print(y.shape)

(1000, 250)
(100, 39)


In [32]:
x=np.asarray(x).astype(np.float32)
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [50]:
y=y[:,1:2]
y = np.asarray(y).astype(np.float32)
print(y)

[]


In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 2]

In [38]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [39]:
model=Sequential()

In [40]:
model.add(Dense(1550,activation='relu'))
model.add(Dense(3000,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=10)

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


NameError: name 'x_train' is not defined

In [52]:
model.save('ramen.h5')

In [53]:
text= "i love the ramen"
text=re.sub('[^a-zA-Z]',' ',text)
text=text.lower()
text=text.split()
text=[ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
text=' '.join(text)

In [57]:
y_p1= model.predict(cv.transform([text]))
y_p1=y_p1>0.7
y_p1

ValueError: Please provide as model inputs either a single array or a list of arrays. You passed: x=  (0, 108)	1
  (0, 165)	1

In [56]:
text

'love ramen'