In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = pd.read_csv('bank.csv')

In [3]:
data.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may      1042         1     -1         0  unknown     yes  
1  unknown    5   may      1467         1     -1         0  unknown     yes  
2  unknown    5   may      1389         1     -1         0  unknown     yes  
3  unknown    5   may       579         1     -1         0  unknown     yes  
4  unknown    5   may       673         2     -1         0  unknown     yes  
5  unknown    5   may       562         2     -1         0  unknown     yes  
6  unknown    6   may      1201         1     -1         0  unknown     yes  
7  unknown    6   may      1030         1     -1         0  unknown     yes  
8  unknown    6   may       608         1     -1         0  unknown     yes  
9  unknown    6   may      1297         3     -1         0  unknown     yes

In [4]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
inputs = data.iloc[:, :16].values
outputs = data.iloc[:, -1:].values

In [6]:
inputs[0:2]

array([[59, 'admin.', 'married', 'secondary', 'no', 2343, 'yes', 'no',
        'unknown', 5, 'may', 1042, 1, -1, 0, 'unknown'],
       [56, 'admin.', 'married', 'secondary', 'no', 45, 'no', 'no',
        'unknown', 5, 'may', 1467, 1, -1, 0, 'unknown']], dtype=object)

In [7]:
outputs.shape

(11162, 1)

In [8]:
outputs

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [10]:
ct = ColumnTransformer([('one', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
inputs = ct.fit_transform(inputs)

cto = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
outputs = cto.fit_transform(outputs)

In [11]:
inputs.shape

(11162, 51)

In [12]:

inputs

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [13]:
outputs

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(inputs,outputs,test_size = 0.2, random_state = 0)

In [17]:
print('Inputs shape ', inputs.shape)
print('Outputs shape ', outputs.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (11162, 51)
Outputs shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)


In [18]:
from sklearn.preprocessing import StandardScaler

In [20]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [21]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [22]:
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         2.62409874,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         1.30248101,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.51893725,
        -0.46885387, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612]])

# ANN MODELLING

In [23]:
from tensorflow.keras.models import Sequential  
from tensorflow.keras.layers import Dense

In [24]:
categorical = Sequential()

In [25]:
categorical.add(Dense(units = 51, kernel_initializer = 'random_uniform', activation = 'relu'))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [26]:
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [27]:
categorical.add(Dense(units = 102, kernel_initializer = 'random_uniform', activation = 'relu'))

In [28]:
categorical.add(Dense(units = 2, kernel_initializer = 'random_uniform', activation = 'softmax'))

In [29]:
categorical.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [30]:
categorical.fit(x_train, y_train, epochs = 50)

Epoch 1/50
8929/8929 [==============================] - 1s 127us/sample - loss: 0.4332 - acc: 0.7989
Epoch 2/50
8929/8929 [==============================] - 1s 92us/sample - loss: 0.3565 - acc: 0.8493
Epoch 3/50
8929/8929 [==============================] - 1s 115us/sample - loss: 0.3434 - acc: 0.8571
Epoch 4/50
8929/8929 [==============================] - 1s 117us/sample - loss: 0.3336 - acc: 0.8615
Epoch 5/50
8929/8929 [==============================] - 1s 100us/sample - loss: 0.3233 - acc: 0.8655
Epoch 6/50
8929/8929 [==============================] - 1s 107us/sample - loss: 0.3166 - acc: 0.8703
Epoch 7/50
8929/8929 [==============================] - 1s 117us/sample - loss: 0.3131 - acc: 0.8684
Epoch 8/50
8929/8929 [==============================] - 1s 111us/sample - loss: 0.3045 - acc: 0.8767
Epoch 9/50
8929/8929 [==============================] - 1s 106us/sample - loss: 0.2963 - acc: 0.8779
Epoch 10/50
8929/8929 [==============================] - 1s 95us/sample - loss: 0.2934 - acc

In [31]:
ypred = categorical.predict(x_test)

In [32]:
ypred[0]

array([9.9980789e-01, 1.9212929e-04], dtype=float32)

In [33]:
ypred[0]>0.5

array([ True, False])

In [34]:
data.head(100)

age            job   marital  education default  balance housing loan  \
0    59         admin.   married  secondary      no     2343     yes   no   
1    56         admin.   married  secondary      no       45      no   no   
2    41     technician   married  secondary      no     1270     yes   no   
3    55       services   married  secondary      no     2476     yes   no   
4    54         admin.   married   tertiary      no      184      no   no   
5    42     management    single   tertiary      no        0     yes  yes   
6    56     management   married   tertiary      no      830     yes  yes   
7    60        retired  divorced  secondary      no      545     yes   no   
8    37     technician   married  secondary      no        1     yes   no   
9    28       services    single  secondary      no     5090     yes   no   
10   38         admin.    single  secondary      no      100     yes   no   
11   30    blue-collar   married  secondary      no      309     yes   no   
12   29     management   married   tertiary      no      199     yes  yes   
13   46    blue-collar    single   tertiary      no      460     yes   no   
14   31     technician    single   tertiary      no      703     yes   no   
15   35     management  divorced   tertiary      no     3837     yes   no   
16   32    blue-collar    single    primary      no      611     yes   no   
17   49       services   married  secondary      no       -8     yes   no   
18   41         admin.   married  secondary      no       55     yes   no   
19   49         admin.  divorced  secondary      no      168     yes  yes   
20   28         admin.  divorced  secondary      no      785     yes   no   
21   43     management    single   tertiary      no     2067     yes   no   
22   43     management  divorced   tertiary      no      388     yes   no   
23   43    blue-collar   married    primary      no     -192     yes   no   
24   37     unemployed    single  secondary      no      381     yes   no   
25   35    blue-collar    single  secondary      no       40     yes   no   
26   31     technician    single   tertiary      no       22     yes   no   
27   43    blue-collar    single  secondary      no        3     yes   no   
28   31         admin.   married  secondary      no      307     yes   no   
29   28    blue-collar    single  secondary      no      759     yes   no   
..  ...            ...       ...        ...     ...      ...     ...  ...   
70   60       services    single    primary      no      313     yes   no   
71   29     management   married   tertiary      no    10576      no   no   
72   41        retired  divorced    primary      no     -233     yes   no   
73   41    blue-collar   married    primary      no     2453     yes   no   
74   42     technician    single  secondary      no     1364     yes   no   
75   36       services    single    unknown      no      281     yes   no   
76   39     technician   married   tertiary      no       94     yes  yes   
77   31  self-employed    single   tertiary      no      144     yes   no   
78   26    blue-collar   married  secondary      no      246     yes   no   
79   31    blue-collar   married  secondary      no       92     yes   no   
80   29         admin.    single  secondary      no      163     yes  yes   
81   37       services  divorced  secondary      no       49     yes   no   
82   33    blue-collar    single  secondary      no     -416     yes   no   
83   24     technician    single  secondary      no      409     yes   no   
84   50         admin.  divorced  secondary      no      363     yes   no   
85   27     technician    single   tertiary      no     3706     yes   no   
86   54     management    single   tertiary      no     4393     yes   no   
87   30     technician    single  secondary      no      863     yes   no   
88   34    blue-collar   married    primary      no      695     yes  yes   
89   37     management    single  secondary      no      792     yes   no   


In [35]:
yp = categorical.predict(sc.transform(ct.transform([[40, "management", "married", "secondary", "no", 4025, "yes", "no", "cellular", 15, "jul", 107, 4, -1, 0, "unknown"]])))

In [36]:
yp

array([[0., 1.]], dtype=float32)

In [37]:
deposits = ['No', 'Yes']
prediction = deposits[np.argmax(yp)]
prediction

'Yes'

In [38]:
np.argmax(yp)

1